# NOTE
#  this is what we get from running
#  kubectl get pods -o yaml > output.yaml
#  This is a bit different from the yamal file we applied using kubectl apply
#  kubectl adds a few things for us as a defaults.
apiVersion: v1
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"k8s-app":"static-web-app-advanced","k8s-scope":"gke-ws-doit-lab-02"},"name":"static-web-app-advanced","namespace":"doit-lab-02"},"spec":{"containers":[{"env":[{"name":"C_MESSAGE","value":"Stay Awhile \u0026 Listen; Lab-2"}],"image":"doitlabs/web-app-static:1.0.5","name":"001-static-web-app-c","ports":[{"containerPort":80,"name":"http-80","protocol":"TCP"}]},{"args":["while true; do echo \"I'm really busy right now ... please come back later!\"; sleep 30; done;"],"command":["sh","-c"],"image":"busybox:1.28","name":"002-static-web-app-sidecar-c"}],"initContainers":[{"command":["sysctl","-w","vm.max_map_count=262144"],"image":"busybox:1.28","name":"000-static-web-app-advanced-init-c","securityContext":{"privileged":true}}]}}
      creationTimestamp: "2022-03-28T10:27:44Z"
      labels:
        k8s-app: static-web-app-advanced
        k8s-scope: gke-ws-doit-lab-02
      name: static-web-app-advanced
      namespace: doit-lab-02
      resourceVersion: "2500"
      uid: cdace634-c770-4551-a438-25a5e9780983
    spec:
      containers:
        - env:
            - name: C_MESSAGE
              value: Stay Awhile & Listen; Lab-2
          image: doitlabs/web-app-static:1.0.5
          imagePullPolicy: IfNotPresent
          name: 001-static-web-app-c
          ports:
            - containerPort: 80
              name: http-80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-h754x
              readOnly: true
        - args:
            - while true; do echo "I'm really busy right now ... please come back later!";
              sleep 30; done;
          command:
            - sh
            - -c
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          name: 002-static-web-app-sidecar-c
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-h754x
              readOnly: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      initContainers:
        - command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          name: 000-static-web-app-advanced-init-c
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-h754x
              readOnly: true
      nodeName: gke-workshop-doit-meera-default-pool-1826614e-ldnl
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
      volumes:
        - name: kube-api-access-h754x
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  expirationSeconds: 3607
                  path: token
              - configMap:
                  items:
                    - key: ca.crt
                      path: ca.crt
                  name: kube-root-ca.crt
              - downwardAPI:
                  items:
                    - fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
                      path: namespace
    status:
      conditions:
        - lastProbeTime: null
          lastTransitionTime: "2022-03-28T10:27:45Z"
          status: "True"
          type: Initialized
        - lastProbeTime: null
          lastTransitionTime: "2022-03-28T10:27:51Z"
          status: "True"
          type: Ready
        - lastProbeTime: null
          lastTransitionTime: "2022-03-28T10:27:51Z"
          status: "True"
          type: ContainersReady
        - lastProbeTime: null
          lastTransitionTime: "2022-03-28T10:27:44Z"
          status: "True"
          type: PodScheduled
      containerStatuses:
        - containerID: containerd://667258c9dc9c3994ff4cdeb792a2af771858ad7294f17a9174af0285381416f3
          image: docker.io/doitlabs/web-app-static:1.0.5
          imageID: docker.io/doitlabs/web-app-static@sha256:000141c30521fae635e870bfc3039eb58dc84225780df5f39600fc0966bab42f
          lastState: {}
          name: 001-static-web-app-c
          ready: true
          restartCount: 0
          started: true
          state:
            running:
              startedAt: "2022-03-28T10:27:50Z"
        - containerID: containerd://3b13bbc9537e2bcb138f1ec803d11b4a1d0b06eeeacbc2a0c934e90d3c8244cb
          image: docker.io/library/busybox:1.28
          imageID: docker.io/library/busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47
          lastState: {}
          name: 002-static-web-app-sidecar-c
          ready: true
          restartCount: 0
          started: true
          state:
            running:
              startedAt: "2022-03-28T10:27:50Z"
      hostIP: 10.132.0.39
      initContainerStatuses:
        - containerID: containerd://77701498577746ad625490d7b9f0f2854e6feaad2994e85e4df0c46a1432d477
          image: docker.io/library/busybox:1.28
          imageID: docker.io/library/busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47
          lastState: {}
          name: 000-static-web-app-advanced-init-c
          ready: true
          restartCount: 0
          state:
            terminated:
              containerID: containerd://77701498577746ad625490d7b9f0f2854e6feaad2994e85e4df0c46a1432d477
              exitCode: 0
              finishedAt: "2022-03-28T10:27:45Z"
              reason: Completed
              startedAt: "2022-03-28T10:27:45Z"
      phase: Running
      podIP: 10.72.1.6
      podIPs:
        - ip: 10.72.1.6
      qosClass: BestEffort
      startTime: "2022-03-28T10:27:44Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
